### ISSUE TITLE
Classify Quarantine type to 5 types only. Subtypes are there only for the TWR and the TQ

### ISSUE THREAD

**Issue by anto-repo** [chennaitricolor/gcc-isolation-tracker#17]
1. PPH - Positive Patients Homes
2. Contacts
3. TWR - Tested and Waiting for Results
    Sub Type [GCC Lab , Govt. Lab, Pvt. Lab]
4. TQ - Travel Quarantine
   Sub Type - [International Flight, Domestic Flight State,Domestic Flight District,Sea Port,Inter State Train,Inter State Road,Inter District Road]
5. FC - Fever Clinics

**Comment by satya64** [comment]
made changes  and updated schema
