### ISSUE TITLE
App : 1 : List of Roles and City 

### ISSUE THREAD

**Issue by anto-repo** [chennaitricolor/gcc-isolation-tracker#8]
Roles in the exact order
1. (_Corporation Name_) staffs 
2. Citizen 
3. Testing centers
4. Treatment centers
5. Health worker
6. Volunteer
7. Admin
8. NGOs 

 An API will provide this based on the Region (

1. GCC
2. Madurai
3. Chengalpattu

**Comment by satya64** [comment]
completed
